name: test

on:
  push:
    paths-ignore:
      - "README*"
      - "docs/*"
  pull_request:
    paths-ignore:
      - "README*"
      - "docs/*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version: ['1.0.x', '1.2.x', 'stable']
    steps:
      - uses: actions/checkout@v1
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
      - name: Install test
        run: nimble install -Y
      - name: Unit test
        run: nimble test -Y
      - name: Examples test
        run: |
          find examples/ -mindepth 1 -type d | while read -r dir; do
            (
              cd "$dir"
              nim c -d:release main.nim
              ./main
            )
          done

  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version: ['stable']
    steps:
      - uses: actions/checkout@v1
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
      - run: nimble doc --index:on --project --out:.out src/pnm.nim
